on:
  push:
    branches:
      - main
      # all branches with a prefix of "releases/"
      - "releases/**"
  pull_request:
    branches:
      - main
      - "releases/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Run Test
        run: npm test
